### ISSUE TITLE
Visual Studio 2017 and inttypes.h

### ISSUE THREAD

**Issue by kdekker** [lexxmark/winflexbison#29]
When I use latest win_flex.exe, the code produced, even in --wincompat mode contains lines like:

```
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN       
```

Unfortunately, Visual Studio does not set __STDC_VERSION__ but has inttypes.h. Because the #else part of the code is used, duplicate macros for e.g. INT8_MIN will exist (and raise an compiler warning or even error if C4005 is marked as error, as was done in our case). Example:

> 1>  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\stdint.h(48): error C4005: 'INT8_MIN': macro redefinition
> 1>  t:\obj.dbg.winx64\lib\sql\libsql_c\sqllex.cpp(57): note: see previous definition of 'INT8_MIN'
> 1>  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\stdint.h(49): error C4005: 'INT16_MIN': macro redefinition
> 1>  t:\obj.dbg.winx64\lib\sql\libsql_c\sqllex.cpp(60): note: see previous definition of 'INT16_MIN'

Can you please enhance this macro and add a check on _MSCVER? The inttypes.h file is (at least) in any Windows 10 SDK. The other approach is to include stdint.h, which is - at least - existent for Visual Studio 2017 and later.

Any other suggestions are welcome.

**Comment by lexxmark** [comment]
I use the following lines to avoid warnings:
%top{
#include <stdint.h>
}

It seems it's already fixed in the original repo [issue#307](https://github.com/westes/flex/issues/307).
Should be available in the next flex release 2.6.5

Let's wait for the next release.

**Comment by Slayer95** [comment]
Sorry. It looks like https://github.com/westes/flex/pull/309 was never ported to winflexbison, as I am still seeing redefinition warnings. Why was this issue closed?

**Comment by lexxmark** [comment]
Fixed on dev in a4305c7 (https://github.com/lexxmark/winflexbison/commit/a4305c7fe027e87437a49c409f3efce546b65b68), ships in 2.5.26.

MSVC never defines __STDC_VERSION__ in C++ mode, so the generated scanner always took the non-C99 branch and defined INT8_MIN plus eight more limit macros. <iostream>, a few lines later, pulls in the SDK's <stdint.h>, which defines them again — 9 × C4005 in every C++ scanner.

Upstream fixed this in 5574881 (https://github.com/westes/flex/commit/5574881ff4c9b08c73b6acc0087d6046c2b48de5) (March 2018): the typedefs moved into a new src/flexint_shared.h, and the skeleton includes that instead of flexint.h, so generated scanners carry no limit macros at all. It landed ten months after the 2.6.4 tag and there has been no flex release since, which is why this port never got it. Backported as-is.

Also added a test. flex.flexint_h_stdint_cxx compiles a generated C++ scanner with /we4005. The existing flex.flexint_h_stdint only covered a C scanner, where nothing includes <stdint.h> afterwards, so it passed either way and never caught this.
